version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scheduler-ttl-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16s0xrgyf24d2"
s3_prefix = "scheduler-ttl-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

