const ABOUT_TYPES = {
  EDUCATION_LEVEL: {
    INCOMPLETE_ELEMENTARY_SCHOOL: "ENSINO FUNDAMENTAL INCOMPLETO",
    ELEMENTARY_SCHOOL: "ENSINO FUNDAMENTAL COMPLETO",
    INCOMPLETE_HIGHSCHOOL: "ENSINO MÉDIO INCOMPLETO",
    HIGHSCHOOL: "ENSINO MÉDIO COMPLETO",
    INCOMPLETE_COLLEGE: "ENSINO SUPERIOR INCOMPLETO",
    COLLEGE: "ENSINO SUPERIOR COMPLETO",
  },
  MARITAL_STATUSES: {
    MARRIED: "CASADO",
    REGISTERED_STABLE_UNION: "UNIÃO ESTÁVEL REGISTRADA",
    NOT_REGISTERED_STABLE_UNION: "UNIÃO ESTÁVEL NÃO REGISTRADA",
    SINGLE: "SOLTEIRO",
    DIVORCED: "DIVORCIADO",
    WIDOWER: "VIÚVO",
  },
  BIRTH_DATE: "DATA DE NASCIMENTO",
};
