---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Creates one stack to test DeletionPolicy=Retain

Parameters:

  Projeto:
    Type: String
    Default: "checkDeletionPolicyRetainAndDeleteMe"

  Ambiente:
    Type: String
    AllowedValues: ["canary"]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain 
    Properties:
      UserPoolName: !Sub "${Projeto} - ${Ambiente}"
      UsernameAttributes:
        - email
      Schema:
        - Name: name
          Mutable: False
          Required: True
        - Name: phone_number
          Required: True
      AutoVerifiedAttributes:
        - email
      UserPoolTags:
        Projeto: !Ref Projeto
        Ambiente: !Ref Ambiente

